# -*- coding: utf-8 -*-
"""Live session:  Getting Started with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tH1hD4hUiNuzXJ3Im2qKb3AS9X7BSDI4
"""

# variables
num = 10
print(num)

first_name = "Alina"
print(first_name)

import keyword
print(keyword.kwlist)

# False = "hello" #not allowed

# Basic Datatypes
# integer
salary = 90000
print(salary)
print(type(salary))

price = int(100)
print(price)

# float
sample = 5.6
print(sample)
print(type(sample))

# float()

# complex: in the form of a + bi, where i imaginary(square root of 1)
a = 4 + 6j
print(a)
print(type(a))

# Bool
isVerified = True
print(isVerified)
print(type(isVerified))

# bool()

# Strings
# single line
name = "Alex"
print(name)
print(type(name))

# multi-line string
text = '''
hello
hi
world
'''
print(text)

# str()

# Advance Datatypes
# List: ordered data, mutable, allows duplicates, []
# list elements
numbers = [10, 20, 30, 40, 50]
print(numbers)
print(type(numbers))

# list()

colors = ["pink", "green", "red", 20]
print(colors)
print(type(colors))

print(len(colors))
print(sum(numbers))
print(colors[0])

# nested list
a = [[10, 20, 30], True]
print(a)

# Tuples: immutable, allow duplicates
a = (100, 200, 300, 400, 500)
print(a)
print(type(a))

print(a[1])

# tuple()

# nested tuple
x = ((10, 30), (100, 30), [10, 20])
print(x)

# SET: store no duplicate, unordered, mutable
languages = {"sql", "python", "java", "javascript", "java"}
print(languages)
print(type(languages))

# nested set is not allowed

# set()

# Dictionary: key value pair, mutable, duplicate keys are not allowed
person = {'name': "alina", 'age': 20, 'age': 30, 'contact': ["admin@gmail.com"]}
print(person)
print(type(person))

print(person["name"])
print(person.values())
print(person.keys())
print(person.items())

# indexing and slicing

# string
string = "Python is a important programming language!"
print(string[1])

print(string[1:4]) #extract string from 1st index till 3rd index
print(string[:20]) #start till 19th index
print(string[10:]) #start from 10th index till index
print(string[2: 11: 2])  #from 2nd till 10th index, every second character

# negative index
x = "Python"
print(x[-1])
print(x[-4: -1]) #extract string from -4 till -2

print(x[-5: -2: -1])

# List
colors = ["pink", "green", "red", "orange", "blue", "violet", "pink"]
print(colors[1])

print(colors[1: 4])
print(colors[:3])
print(colors[2:])
print(colors[1:4:2])
print(colors[::-1]) #reverse a list

print(colors[-2])
print(colors[-5: -2])

# Tuples
a= (10, 30, 40, 50)
print(a[0])

print(a[1: 4])

# similar as above

# dict
product = {"title": "Laptop-1", 'price': 90900, 'mYear': 2024, 'similarProduct': ['Tab', 'Laptop', 'TV'] }
print(product["title"])
print(product["similarProduct"][1])

# strings are immutable
# s = "1992"
# s[0] = 29 #error
# print(s)

# count of character or words
print(colors.count("pink"))

# Operators

# Arithmetic: addition, subtraction, multiply, divide, modulus, floor division, power
a = 200
b = 100
print(a + b)
print(a * b)
print(a - b)
print(a % b) #remainder
print(a / b)  #as it is
print(a // b) #integer

# assignment  (=)
# comparison operator (==, >, >, <=, >=, !=) (output is in boolean)
print(a != b)

# logical operators (and, or, not) (output is in boolean)
print(a != b and a == b)
print(not(a != b))

# identity operators (== -> is != => is not) (output is in boolean)
print(a is b)

# membership operators ('in' and 'not in') (output is in boolean)
text = "Python"
print("on" in text)

# Bitwise operator

# List
a= [10, 20, 40]
b = [100, 200, 400]
print(a + b)

print(a * 2)

# Tuples
a= (10, 2, 4, 5)
b = (100, 200, 300)
print(a + b)

print(a * 2)

# set
a= {1, 2, 4}
b = {10, 20, 30}
print(a | b)

# inbuilt Functions

# 1. print()
# 2. type ()
# 3. len(): is ued to find the length of the objects(string, tuple, list, set, dict)
a ="hello"
print(len(a))

a = {1, 2, 3}
print(len(a))

a = [10, 2, 4, 20]
print(len(a))

a = (10, 2, 4, 5)
print(len(a))

a= {'name': "alina", 'age': 20}
print(len(a))

# 4. sum(): is used to the sum of tuple, list, set
a = [10, 20, 4, 5]
b = {10, 3, 5}
c = (10, 3, 5)
print(sum(a))
print(sum(b))
print(sum(c))

# 5. min:  is used to the min of tuple, list, set
print(min(a))
print(min(b))
print(min(c))

# 6. max: is used to the max of tuple, list, set
print(max(a))
print(max(b))
print(max(c))

# 7. abs: -ve to +ve
print(abs(-100))

# 8. round: is used to round off to nearest decimal place
print(round(199.847900, 2)) #riund upto 2 decimal places

# 9. range()
print(list(range(0, 11)))
print(tuple(range(0, 11)))
print(list(range(3, 31, 3)))
print(list(range(-10, -4)))
print(list(range(-1, -11, -1)))

# 10. enumerate(): find the index of each element/character in th object(set, tuple, list)
a= "python"
print(list(enumerate(a)))

a = [10, 2, 3, 4]
print(list(enumerate(a)))

a = {1, 2, 4, 5}
print(list(enumerate(a)))

# 11. int(): it is used to define integer value.
# string to int, float to int, bool to int
print(int("20"))
# print(int("cudhci")) #error
print(int(True))
print(int(False))
print(int(10.27))

# 12. float(): int to float, bool to float, str to float
# 13. bool(): float to bool, int to bool str to bool
# 14. str(): convert boolean, int, float to string

# 15. input(): is used to take user input
a = int(input());
a = float(input())
a= bool(input())

# 16. eval() for input for list tuple, set, dict
a = eval(input("Please enter"))

# 17. sum(): already discussed above
# 18. values(): already discussed above
# 19. keys(): already discussed above
# 20. items(): already discussed above

# 21. exec(): writing mutiple lines of code in a single line
a = 10
b = 20
print(a + b)
exec('a=10\nb=20\nprint(a+b)')

# 22. zip: is used to create nested list, tuple, set
a = ["name", "age"]
b = ["2", "3"]
print(list(zip(a, b)))
print(tuple(zip(a, b)))
print(set(zip(a, b)))

# 22. help(): explain anything
print(help(sum))

# String methods
# upper(), lower(), capitalize(), title(), swapcase(), count(), index(), replace, split(), join(), strip()
strVal = "hello world"
print(strVal.swapcase())
print(strVal.upper())
print(strVal.lower())
print(strVal.capitalize())
print(strVal.title())
print(strVal.count("o"))
print(strVal.index("o"))
print(strVal.find("O")) #return -1 if not found

string = "Python is important"
print(string.replace("Python", "JavaScript"));

print(string.split(" "))

sample= 'kmdl-dieodi-deidje-jk'
print(sample.split("-"))

# strip() : removing leading and trailing
new_str = "   hijdie diedied diedi oeid  "
print(new_str.strip())

new_str_val = "*****uhdued***"
print(new_str_val.strip("*"))
print("**********deid*****".lstrip("*"))
print("**********deid*****".rstrip("*"))

list_val = ["hello", "hi", "world"]
print("-".join(list_val))
print("*".join(list_val))

# List methods
# reverse(), sort, copy, append(), count(), insert(), CRUD, extend, drop, clear, delete, pop
colors = ["green", "orange", "pink", "blue", "white", "pink"]

colors.reverse()
print(colors)

numbers = [10, 3, 30, 50, 100]
numbers.sort()
print(numbers) #by default: asc

numbers.sort(reverse = True) #sort in desc order
print(numbers)

print(numbers.copy())

# count
print(colors.count("pink"))

# CRUD
# add a new element
fruits = ["apple", "orange", "grapes", "mango"]
fruits.append("strawberry") #always add in the end
print(fruits)

# insert()
fruits.insert(1, "dragon fruit")
print(fruits)

# update
fruits[0] = "Apple"
print(fruits)

# extend : combine the list
a = [1, 2, 4]
b = [6, 7, 9]
a.extend(b)
print(a)

a.remove(1) #delete a specific value
print(a)

a.pop() #remove the last element
print(a)

a.pop(1) #where 1 is index
print(a)

# clear: delete all the elements
a.clear()
print(a)

# delete the list
# del a
# print(a) #error as list "a" is deleted

# Tuple methods
# count, index
a = (1, 2, 4, 5 ,6, 1, 2)
print(a.count(1))
print(a.index(5))

print(sorted(a))  #asc
print(sorted(a, reverse =True)) #desc

# Set Methods
# add, update, remove, discard, pop, clear, delete

a = {1, 2, 3, 4, 5 ,6}
a.add(10)
print(a)

a.remove(4)
print(a)

# a.remove(100) #it will give error, if element we are trying to remove doesn't exist in SET
# print(a)

a.discard(100)
print(a)

a.pop()
print(a)

a.clear()
print(a)

# union
a = {1, 2, 3, 4}
b = {1, 2, 5, 6}
print(a.union(b))

# intersection
print(a.intersection(b))

# difference (a - b): all the elements of a which are not in b
print(a.difference(b))

# (b - a): all the elements of b which are not in a
print(b.difference(a))

# Dictionary methods
# keys(), values(), items()
person = {'name': "alina", 'age': 20, 'city': 'Pune'}
print(person["name"])

# get
print(person.get('name'))

# modify
person.update({'age': 30})
print(person)

person.setdefault('salary', 809090)
print(person)

# to delete
person.pop("salary")
print(person)

person.popitem()
print(person)

person.clear()
print(person)

# del person
# print(person) #error