# -*- coding: utf-8 -*-
"""Live session: Python in Depth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U90Ipso4lnevG0qL-ElT6B2Yt2nlF6Qh
"""

# conditional statements
# if
x = 20;
if x > 10:
  print(f"{x} is greater than 10")

print("this outside!")

# elif, else
weather = "rainy"

if weather == "sunny":
  print("Lets go out for a lunch!")
elif weather == "rainy":
  print("Take a umbrella.")
else:
  print("Stay indoor")

# nested if statements
age = 20
has_id = True

if age >= 18:
  if has_id:
    print("You can enter the building!")
  else:
    print("You cant enter")
else:
  print("You are tool young to enter!")

# multiple condition using logical operators
score = 80
attendence = 90

if score >= 80 and attendence >= 75:
  print("Grade A")
elif score >= 60 and attendence >= 60:
  print("Grade B")
else:
  print("Grade C")

# Ternary opertor ( "true output" if (condition) else "false output"
num = 7
result = "Even" if num % 2 == 0 else "Odd"
print(result)

# Loops
# loop on string
my_string = "Python"
for char in my_string:
  print(char)

# loop on list
fruits = ["apple", "orange", "grapes", "cherry"]
for f in fruits:
  print(f"{f} is the fruit")

# loop on tuple
a = (10.9, 29.9, 29, 49,7)
for point in a:
  print(f"cordinates: {point}")

# loop on set
numbers = {1, 2, 3, 4,5 ,7}
for n in numbers:
  print(f"{n} is the set nunber")

# dictionary
student_grades = {"alina": 90, "alex": 80, "alishka": 60, "alaya": 70}
# get the keys (default)
for k in student_grades:
  print(f"{k}: is the key")

# get the value
for k in student_grades.values():
  print(f"{k}: is the value")

# iterate over both keys and values
for st, gr in student_grades.items():
  print(f"{st}: {gr}")

# loop over range
for n in range(0, 11):
  print(n)

for n in range(3, 31, 3):
  print(n)

# nested loops
for i in range(1, 6):
  for j in range(1, 5):
    print(f"{i}, {j}")

# infinite loop
# while True:
#   print("this is a infinite loop")

'''
while condition:
  block of code
  inc/dec statement
'''

countdown = 3
while countdown >= 0:
  print(f"countdown: {countdown}")
  countdown -= 1

# break: termianting the loop
for n in range(1, 10):
  if n == 5:
    print(f"{n} is found")
    break
  print(n)

#  continue: terminate the current iteration
for n in range(1, 10):
  if n == 3:
    continue
  print(n)

def add():
  a = 10
  b = 20
  result = a + b
  print(f"Result: {a} + {b} = {result}")
add()

# parameterised function
def mutltiply(x, y):
  result = x * y
  print(f"Result is:{x} * {y} = {result}")

mutltiply(2, 10)