# -*- coding: utf-8 -*-
"""Live session: Searching Algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8legRCZrvfcxG5iC9CHNhX7r31JnxZS
"""

def linear_search(arr, target):
  for i in range(len(arr)):
    if arr[i] == target:
      return arr[i]
  return - 1

print(linear_search([20, 10, 2, 3, 4, 5], 10))

# Time complexity: O(n)
# Space complexity: O(1)

# Question: list of studeny grades, count how many students scored above 85?

def count_grades(grades):
  count = 0
  for grade in grades:
    if grade >= 85:
      count += 1
  return count

print(count_grades([85, 90, 85, 70, 20]))

# Time complexity: O(n), where n is the length of arr
# Space compelxity: O(1)

def binary_search(arr, target):
  left = 0
  right = len(arr) - 1

  while left <= right:
    mid = (left + right) // 2
    if arr[mid] == target:
      return mid
    elif arr[mid] < target:
      left = mid + 1
    else:
      right = mid - 1
  return -1


print(binary_search([2, 4, 5, 6, 8, 9, 10], 9))

# Time complexity: O(log n), where n is the length of arr
# Space compelxity: O(1)

# find the position/index of target. given array is sorted with duplicates. find the first occurence index fo target value

def first_occurence(arr, target):
  left = 0
  right = len(arr) - 1
  result = -1

  while left <= right:
    mid = (left + right) // 2
    if arr[mid] == target:
      result = mid
      right = mid - 1 #keep searching to the left
    elif arr[mid] < target:
      left = mid + 1
    else:
      right = mid - 1
  return result

print(first_occurence([1, 2, 2, 2, 5], 2));

# Find the peak element: given a integer array, find the peak (element which is greater than its neighbouring elements)

def find_peak(arr):
  left = 0
  right = len(arr) - 1

  while left < right:
    mid = (left + right) // 2
    if arr[mid] < arr[mid + 1]:
      left = mid + 1
    else:
      right = mid
  return left

print(find_peak([1, 2, 3, 1]))

# Jump search
import math

def jump_search(arr, target):
  n = len(arr) #5
  step = int(math.sqrt(n)) #2
  prev = 0

  # find the block
  while prev < n and arr[min(step,) - 1] < target:
    prev = step
    step = step + int(math.sqrt(n))

# linear search
  while prev < n and arr[prev] <= target:
    if arr[prev] == target:
      return prev
    prev += 1

  return - 1

print(jump_search([2, 3, 4, 5, 10], 5))

# Time complexity: sqrt(n)
# Space complexity: O(1)

"""**Tasks on Linear Binary Jump**

**Topic: Linear Search**
1. The Standard Search (First Occurrence)
Given an unsorted array of integers, write a function to return the index of the first occurrence of a target integer. If not found, return -1.

Input: arr = [4, 2, 7, 2, 9], target = 2

Expected Output: 1

2. The Accumulator (Counting Occurrences)
Given a list of student grades, count how many students scored exactly an 85.

Input: grades = [85, 90, 85, 70, 85]

Expected Output: 3

3. The Extremes (Finding Minimum)
Given an array of stock prices for the week, find and return the minimum price.

Input: prices = [120, 115, 130, 110, 125]

Expected Output: 110

4. Condition-Based Search (Filtering)
Given a list of mixed integers, return a new list containing only the even numbers that are strictly greater than 10.

Input: arr = [5, 12, 18, 9, 10, 22]

Expected Output: [12, 18, 22]


5. The Last Occurrence (Reverse Search)
Given an array with duplicate elements, find the index of the last occurrence of the target value.

Input: arr = [4, 2, 7, 2, 9], target = 2

Expected Output: 3

**Topic: Binary Search**
1. The Standard Search (Exact Match)
Given a sorted array of integers, find the index of a target value. Return -1 if not found.

Input: arr = [1, 3, 5, 7, 9], target = 7

Expected Output: 3

2. Search Insert Position
Given a sorted array and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

Input: arr = [1, 3, 5, 6], target = 2

Expected Output: 1

3. First Position of a Target (Lower Bound)
Given a sorted array with duplicates, find the first occurrence index of a given target value.

Input: arr = [1, 2, 2, 2, 5], target = 2

Expected Output: 1

4. Search in a Rotated Sorted Array
A sorted array is rotated at an unknown pivot (e.g., [4, 5, 6, 7, 0, 1, 2]). Search for a target value and return its index.

Input: arr = [4, 5, 6, 7, 0, 1, 2], target = 0

Expected Output: 4

5. Find Peak Element
A peak element is strictly greater than its neighbors. Given an integer array, find a peak element and return its index.

Input: nums = [1, 2, 3, 1]

Expected Output: 2 (since the element '3' is greater than 2 and 1)

6. Valid Perfect Square
Given a positive integer num, write a function which returns True if num is a perfect square, else False. Do not use built-in math libraries.

Input: num = 16

Expected Output: True

**Topic: Jump Search**
1. The Standard Search
Implement jump search on a sorted list to find a target value, returning its index. Return -1 if not found.

Input: arr = [0, 1, 2, 3, 4, 5, 8, 13], target = 5

Expected Output: 5

2. Custom Jump Size
Modify the jump search algorithm to take a specific jump_size as an argument instead of calculating the square root of n. Find the target value and return its index.

Input: arr = [10, 20, 30, 40, 50], target = 40, jump_size = 2

Expected Output: 3

3. Jump Search with Strings
Given an alphabetically sorted list of dictionary words, find the index of a target word using jump search logic.

Input: words = ["apple", "banana", "cherry", "date"], target = "cherry"

Expected Output: 2

4. Find First Element Greater Than Target
Use jump search logic to find the index of the first element in a sorted array that is strictly greater than the target.

Input: arr = [2, 4, 6, 8, 10], target = 5

Expected Output: 2 (the element is 6)

5. Count Target Occurrences in a Block
Given a sorted array with duplicates, use jump search to find the block containing the target, and then count how many times the target appears in the entire array.

Input: arr = [1, 2, 2, 2, 3, 4], target = 2

Expected Output: 3

6. Reverse Jump Search (Descending Order)
Implement jump search for an array sorted in descending order to find a target value's index.

Input: arr = [50, 40, 30, 20, 10], target = 20

Expected Output: 3

"""