# -*- coding: utf-8 -*-
"""Live session:  Arrays and Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B70zQXGRVT_cY_753ZGucev0LHuWUrIR
"""

# Arrays: implementing using list in Python

colors  = ["green", "pink", "blue", "white", "orange"]
# append(), insert(), extend(), pop(), remove(), clear(), count(), sort(), reverse(), slicing

# Strings:
first_name = "Hello Worl!"
# upper(), lower(), swapcase(), find(), index(), title(), replace(), strip(), lstrip(), rstrip(), join(), split(), slicing

# Two Pointer Technique

# check a palindrome string | check if a string reads same forwards and backward
def is_palindrome(s):
  if len(s) == 0:
    return 0
  left = 0
  right = len(s) - 1

  while left < right:
    if s[left].lower() != s[right].lower():
      return False
    left += 1
    right -= 1
  return True



# is_palindrome("racecar")
is_palindrome("abba")

# Reverse a string in place | revsere a list of character in place
def reverse_string(s: list):
  if len(s) == 0:
    return
  left = 0
  right = len(s) - 1

  while left < right:
    # swaping the elemets
    s[left], s[right] = s[right], s[left]
    left += 1
    right -= 1
  return s

string = "hello"
reverse_string(list(string))

def target_sum(numbers: list, target: int):
  left = 0
  right = len(numbers) - 1

  while left < right:
    current_sum = numbers[left] + numbers[right]
    if current_sum == target:
      return [numbers[left], numbers[right]]
    elif current_sum < target:
      left += 1
    else:
      right -= 1
  return []


print(target_sum([2, 7, 11, 7, 15], 9)); #array, target

# arranged in even number followed by odd numbers

def sort_even_odd(arr):
  left = 0
  right = len(arr) - 1

  while left < right:
    if arr[left] % 2 == 0:
      left += 1
    elif arr[right] % 2 != 0:
      right -= 1
    else:
      arr[left], arr[right] = arr[right], arr[left]
      left += 1
      right -= 1
  return arr

print(sort_even_odd([3, 1, 2, 4]))

"""1. Reverse Vowels of a String
Problem: Given a string, reverse only all the vowels in the string and return it. The vowels are 'a', 'e', 'i', 'o', and 'u', and they can appear in both lower and upper cases, more than once.


Input: "leetcode"
Output: "leotcede"

Students Hint: Convert the string to a list first. The left pointer moves right until it finds a vowel. The right pointer moves left until it finds a vowel. When both point to a vowel, swap them!

2. Separate Positives and Negatives
Problem: Given an integer array, move all negative numbers to the left side and all positive numbers to the right side in-place. The order of the numbers does not matter.

Input: [-1, 2, -3, 4, 5, -6]
Output: [-1, -6, -3, 4, 5, 2] (or any other valid arrangement)


Students Hint:   This is identical to the "Sort Array by Parity" question we did. The left pointer looks for a positive number, the right pointer looks for a negative number. When they both find their targets, swap them.

3. Valid Palindrome II (One Deletion allowed)
Problem: Given a string s, return True if the string can be a palindrome after deleting at most one character from it.

Input: "abca"
Output: True (You could delete the 'c' to get "aba")
Students Hint:  Start like a normal valid palindrome using two pointers. If you hit a mismatch, you have two choices: skip the left character OR skip the right character. If either resulting substring is a palindrome, return True!

4. Count Pairs Whose Sum is Less than Target
Problem: Given an array of integers that is already sorted, and a target integer, return the number of pairs (i, j) where i < j and nums[i] + nums[j] < target.

Input: nums = [-1, 1, 2, 3, 1], target = 2 (Assume sorted: [-1, 1, 1, 2, 3])

Output: 3


Students Hint:  If nums[left] + nums[right] < target, it means nums[left] paired with any number between left and right will also be less than the target! Add (right - left) to your total count and move the left pointer up.

5. Container With Most Water
Problem: You are given an integer array heights where each element represents the height of a vertical line on a graph. Find two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum area of water it can store.

Input: [1, 8, 6, 2, 5, 4, 8, 3, 7]
Output: 49


Students Hint: The width is right - left. The height is the minimum of heights[left] and heights[right]. Calculate the area. To find a potentially bigger area, always move the pointer that points to the shorter line inward.
"""